steps:
  - task: PowerShell@2
    displayName: "Download Tabular Editor 2.x"
    inputs:
      targetType: filepath
      filePath: '$(Build.SourcesDirectory)\Power BI Playbook\DevOps\semantic-model-pipelines\scripts\download-te2.ps1'
      pwsh: true